### ISSUE TITLE
Can you share Android App on github

### ISSUE THREAD

**Issue by tombo9999** [longpth/ESP32CamAI#1]
Can you share Android App on github as you did with "[Android-Object-Tracking-OpenCV](https://github.com/longpth/Android-Object-Tracking-OpenCV)"?
I'm trying to make this [small robot](https://hackaday.io/project/18149-xpider-worlds-cutest-spider-robot) open source and your App could be a good start (I'm a total beginner about programming).
See also [Thingiverse](https://www.thingiverse.com/thing:1704879/comments) and [Instructable](https://www.instructables.com/member/Roboeve/)

Thank you in advance, Luca  :)

**Comment by longpth** [comment]
I will share after a while, firstly I need  to remember where I kept it ;)), but I don't have much time now

**Comment by tombo9999** [comment]
Thank you, I'll wait patiently  ;)
